CREATE TABLE EMPLOYEE
(
  employee_ID INTEGER not null,
  E_name CHAR(11),
  contact INTEGER(11),
  address CHAR(20),
  ssn INTEGER not null,
  PRIMARY KEY(employee_ID ),
  PRIMARY KEY(ssn)
);

CREATE TABLE RECORD
( 
  record_number INTEGER,
  PRIMARY KEY (record_number)
  FOREIGN KEY (appointment_ID) REFERENCES APPOINTMENT
 );

CREATE TABLE MAINTAIN
( 
  record_number INTEGER,
  employee_ID INTEGER,
  PRIMARY KEY (record_number, employee_ID),
  FOREIGN KEY (record_number) REFERENCES RECORD,
  FOREIGN KEY (employee_ID) REFERENCES RECEPTIONIST
);

CREATE TABLE APPOINTMENT
( 
  appointment_ID INTEGER,
  doctor_ID INTEGER(11),
  patient_ID INTEGER(11),
  A_time DATE, //time is used by SQL already
  room_ID INTEGER(11), 
  PRIMARY KEY(appointment_ID),
  FOREIGN KEY(room_ID) 
  FOREIGN KEY(doctor_ID) REFERENCES (PATIENT),
  FOREIGN KEY(patient_ID) REFERENCES (DOCTORS)
);

CREATE TABLE BOOK
(
  appointment_ID INTEGER,
  employee_ID INTEGER,
  PRIMARY KEY(appointment_ID, employee_ID),
  FOREIGN KEY (employee_ID) REFERENCES RECEPTIONIST,
  FOREIGN KEY(appointment_ID) REFERENCES APPOINTMENT
);

CREATE TABLE RECEPTIONIST
(
  employee_ID INTEGER not null,
  PRIMARY KEY(employee_ID),
  FOREIGN KEY(record_number) REFERENCES RECORDS,
  FOREIGN KEY(appointment_ID) REFERENCES APPOINTMENT
  FOREIGN KEY (employee_ID) REFERENCES EMPLOYEE 
  	ON DELETE CASCADE
	ON UPDATE SET DEFAULT
);

CREATE TABLE DOCTOR
(
  employee_ID INTEGER not null,
  PRIMARY KEY(employee_ID),
  FOREIGN KEY (employee_ID) REFERENCES EMPLOYEE
	ON DELETE CASCADE,
	ON UPDATE SET DEFAULT
);

CREATE TABLE VISITING_DOCTOR
(
  start_date DATE,
  end_date DATE,
  employee_ID  INTEGER,
  PRIMARY KEY(employee_ID),
  FOREIGN KEY (employee_ID) REFERENCES DOCTOR
	ON DELETE CASCADE,
	ON UPDATE SET DEFAULT
);

CREATE TABLE CONTRACT_DOCTOR
(
  contract_ID INTEGER,
  employee_ID  INTEGER,
  PRIMARY KEY(employee_ID),
  FOREIGN KEY (employee_ID) REFERENCES DOCTOR
	ON DELETE CASCADE,
	ON UPDATE SET DEFAULT
);





CREATE TABLE TRAINEE_DOCTOR
(
  start_date DATE,
  end_date DATE,
  employee_ID  INTEGER,
  PRIMARY KEY(employee_ID),
  FOREIGN KEY (employee_ID) REFERENCES DOCTOR
	ON DELETE CASCADE,
	ON UPDATE SET DEFAULT
)

CREATE TABLE NURSE
(
  shift DATE, //for time slot  
  room_ID INTEGER, 
  employee_ID  INTEGER,
  PRIMARY KEY (employee_ID ),
  FOREIGN KEY(room_ID) REFERENCES (ROOM)
  FOREIGN KEY (employee_ID) REFERENCES EMPLOYEE
	ON DELETE CASCADE,
	ON UPDATE SET DEFAULT
)

CREATE TABLE REPORTS_TO
(
  doctor_ID INTEGER,
  nurse_ID INTEGER,
  PRIMARY KEY (doctor_ID, nurse_ID),
  FOREIGN KEY(doctor_ID) REFERENCES DOCTOR
	ON DELETE CASCADE,
  FOREIGN KEY( nurse_ID) REFERENCES NURSE
	ON DELETE CASCADE
)

CREATE TABLE ROOM
(
  room_ID INTEGER, 
  room_type CHAR(11),
  DURATION DATE,
  Start_Date DATE,
  End_Date DATE,
  employee_ID INTEGER,
  PRIMARY KEY (room_ID),
  FOREIGN KEY(employee_ID) REFERENCES NURSE
)





CREATE TABLE GOVERNS
(
  nurse_ID INTEGER,
  room_ID INTEGER,
  PRIMARY KEY(nurse_ID, room_ID),
  FOREIGN KEY(nurse_ID) REFERENCES NURSE
  FOREIGN KEY(room_ID) REFERENCES ROOM
	ON DELETE CASCADE
)

CREATE TABLE ASSIGNED_TO
(
  P.I.D INTEGER,
  room_ID INTEGER,
  PRIMARY KEY(P.I.D, room_ID),
  FOREIGN KEY(P.I.D) REFERENCES PATIENT,
  FOREIGN KEY(room_ID) REFERENCES ROOM
)

CREATE TABLE ATTENDED_BY
(
  P.I.D INTEGER,
  doctor_ID INTEGER,
  PRIMARY KEY(P.I.D, doctor_ID), 
  FOREIGN KEY(P.I.D) REFERENCES PATIENT,
	ON DELETE CASCADE
  FOREIGN KEY(doctor_ID) REFERENCES DOCTOR
)

 CREATE TABLE PATIENT
(
  P.I.D INTEGER not null,
  name CHAR(11) not null,
  address CHAR(20),
  contact INTEGER(11),
  age INTEGER,
  date_of_admission DATE,
  date_of_discharge DATE,
  PRIMARY KEY(P.I.D)
)




CREATE TABLE BILL_FOR
(
  P.I.D INTEGER,
  bill_ID INTEGER,
  PRIMARY KEY(P.I.D, bill_ID),
  FOREIGN KEY (P.I.D) REFERENCES PATIENT
	ON DELETE CASCADE
	ON UPDATE NO ACTION
)

CREATE TABLE MEDICAL_CARE
(
  bill_ID INTEGER not null,
  price INTEGER not null,
  PRIMARY KEY(bill_ID)
)

CREATE TABLE TREATMENT
(
  treatment_name CHAR(11),
  bill_ID INTEGER not null,
  PRIMARY KEY(bill_ID) ,
  FOREIGN KEY (bill_ID) REFERENCES (MEDICAL_CARE)
	ON DELETE CASCADE
	ON UPDATE SET DEFAULT
)

CREATE TABLE MEDICINE
(
  dose CHAR(11), //in description
  bill_ID INTEGER not null,
  PRIMARY(bill_ID)
  FOREIGN KEY (bill_ID) REFERENCES (MEDICAL_CARE)
	ON DELETE CASCADE
	ON UPDATE SET DEFAULT
)

